{
 "title": "Analytics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Spark Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spark Active Stages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_active_stages\"}"
    }
   ]
  },
  {
   "title": "Spark Active Stages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_active_stages\"}"
    }
   ]
  },
  {
   "title": "Completed Sages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_completed_stages\"}"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_completed_tasks\"}"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"master.apps\"}"
    }
   ]
  },
  {
   "title": "Waiting Apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"master.waitingApps\"}"
    }
   ]
  },
  { "title": "Apps / Jobs / Stages / Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Stages (Active, Completed, Failed, Skipped)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_active_stages\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_completed_stages\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_failed_stages\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_skipped_stages\"}",
     "legendFormat": "Skipped"
    }
   ]
  },
  {
   "title": "Tasks (Active, Completed, Failed, Skipped)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_active_tasks\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_completed_tasks\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_failed_tasks\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.job.num_skipped_tasks\"}",
     "legendFormat": "Skipped"
    }
   ]
  },
  { "title": "Spark Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Number of executors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"worker.executors\"}"
    }
   ]
  },
  {
   "title": "Executor Disk Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.executor.disk_used\"}"
    }
   ]
  },
  {
   "title": "Executor Max Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.executor.max_memory\"}"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.executor.memory_used\"}"
    }
   ]
  },
  {
   "title": "Executor Total Input Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.executor.total_input_bytes\"}"
    }
   ]
  },
  {
   "title": "Executor Shuffle Reads and Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.executor.total_shuffle_read\"}"
    },
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.executor.total_shuffle_write\"}"
    }
   ]
  },
  { "title": "Spark Driver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Driver Disk Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.driver.disk_used\"}"
    },
    {}
   ]
  },
  {
   "title": "Driver Memory (used and max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"spark.driver.max_memory\"}"
    },
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.driver.memory_used\"}"
    }
   ]
  },
  {
   "title": "Driver Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.driver.total_tasks\"}"
    },
    {}
   ]
  },
  {
   "title": "Driver Input Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.driver.total_input_bytes\"}"
    },
    {}
   ]
  },
  {
   "title": "Driver Shuffle Read / Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.driver.total_shuffle_read\"}"
    },
    {
     "expr": "collectd_apache_spark_counter_total{type=\"spark.driver.total_shuffle_write\"}"
    }
   ]
  },
  { "title": "Spark Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Worker Cores (used and free)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"worker.coresUsed\"}"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"worker.coresFree\"}"
    }
   ]
  },
  {
   "title": "Worker Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"worker.memFree_MB\"}"
    },
    {
     "expr": "collectd_apache_spark_gauge{type=\"worker.memUsed_MB\"}"
    }
   ]
  },
  { "title": "Spark Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Apps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"master.apps\"}"
    }
   ]
  },
  {
   "title": "Waiting Apps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"master.waitingApps\"}"
    }
   ]
  },
  {
   "title": "Alive Workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"master.aliveWorkers\"}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_apache_spark_gauge{type=\"master.workers\"}"
    }
   ]
  }
 ]
}