{
 "title": "DSE System & Node Metrics",
 "tags": [ "dse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{}, cluster)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.datastax.com\" target=\"new\"><img src=\"https://www.datastax.com/sites/default/files/2020-12/datastax-logotype-negative.png\"/></a>"
   }
  },
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - ((sum(irate(collectd_cpu_total{instance='$host', type='idle'}[$rate])) by (instance) /  \n                  sum(irate(collectd_cpu_total{instance='$host'}[$rate])) by (instance)))) * 100"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "description": "Amount of memory used (ignoring page cache)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ((sum(collectd_memory{instance=\"$host\", memory=\"free\"}) + sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) + sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})) / sum(collectd_memory{instance=\"$host\"}))"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(collectd_swap{instance='$host',swap='used'}) / sum(collectd_swap{instance='$host'})) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(collectd_df_df_complex{instance='$host',df=\"root\",type=\"used\"}) / sum(collectd_df_df_complex{instance='$host',df=\"root\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(collectd_load_shortterm{instance='$host'}) / count(count(collectd_cpu_total{instance='$host'}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(collectd_load_midterm{instance='$host'}) / count(count(collectd_cpu_total{instance='$host'}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(collectd_cpu_total{instance='$host'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_memory{instance='$host'})"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_swap{instance='$host'})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{df=\"root\",instance='$host'})"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_load_shortterm{instance='$host'}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_uptime{instance='$host'}"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='system'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='user'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='wait'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='softirq'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(rate(collectd_cpu_total{instance='$host',type!='idle',type!='system',type!='user',type!='wait',type!='softirq'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='idle'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=~\"$host\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(collectd_memory{instance=~\"$host\"}) - sum(collectd_memory{instance=~\"$host\", memory=\"free\"}) - sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) - sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) + sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(collectd_memory{instance=\"$host\", memory=\"free\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(collectd_swap{instance=\"$host\"}) - sum(collectd_swap{instance=\"$host\", swap=\"free\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps", "label": "Read (-) /  Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_interface_if_octets_rx_total{instance='$host'}[$rate]) * 8",
     "legendFormat": "{{interface}} read "
    },
    {
     "expr": "irate(collectd_interface_if_octets_tx_total{instance='$host'}[$rate]) * 8",
     "legendFormat": "{{interface}} write"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Read (-) /  Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_interface_if_packets_rx_total{instance='$host'}[$rate])",
     "legendFormat": "{{interface}} read "
    },
    {
     "expr": "irate(collectd_interface_if_packets_tx_total{instance='$host'}[$rate])",
     "legendFormat": "{{interface}} write"
    }
   ]
  },
  {
   "title": "Disk Rate / sec",
   "type": "graph",
   "description": "Read/Write bytes/sec",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_disk_disk_octets_read_total{instance=\"$host\",disk=~\".*\\\\d+\"}[$rate])",
     "legendFormat": "{{disk}} - Reads"
    },
    {
     "expr": "irate(collectd_disk_disk_octets_write_total{instance=\"$host\",disk=~\".*\\\\d+\"}[$rate])",
     "legendFormat": "{{disk}} - Writes"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "description": "iops",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_disk_disk_ops_read_total{instance=\"$host\",disk=~\".*\\\\d+\"}[$rate])",
     "legendFormat": "{{disk}} - Reads completed"
    },
    {
     "expr": "irate(collectd_disk_disk_ops_write_total{instance=\"$host\",disk=~\".*\\\\d+\"}[$rate])",
     "legendFormat": "{{disk}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{instance=\"$host\", type=\"used\"}) by (df)",
     "legendFormat": "{{df}}"
    },
    {}
   ]
  },
  {
   "title": "Disk Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_disk_disk_io_time_weighted_io_time_total{instance=\"$host\",disk=~\".*[0-9]+\"}[$rate]) / 1000",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms", "label": "read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "-irate(collectd_disk_disk_time_read_total{instance='$host',disk=~\".*[0-9]+\"}[$rate])",
     "legendFormat": "{{disk}} - Reads"
    },
    {
     "expr": "irate(collectd_disk_disk_time_write_total{instance='$host',disk=~\".*[0-9]+\"}[$rate])",
     "legendFormat": "{{disk}} - Writes"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"user\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\" }[$rate])) by (cpu) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"system\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\"}[$rate])) by (cpu) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU IOWait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"wait\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\"}[$rate])) by (cpu) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU SoftIRQ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"softirq\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\" }[$rate])) by (cpu) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Other",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=~\"(interrupt|nice|steal)\"}[$rate])) by (cpu, type)  / ignoring(type) group_left sum(rate(collectd_cpu_total{instance=\"$host\" }[$rate])) by (cpu) * 100",
     "legendFormat": "{{cpu}} - {{type}}"
    }
   ]
  },
  {
   "title": "Local Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(dse_table_write_latency_bucket{table=~'.*', keyspace=~'.*', instance='$host'}[$rate])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Advanced Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(irate(collectd_contextswitch_total{instance='$host'}[$rate]))",
       "legendFormat": "ContextSwitches"
      }
     ]
    },
    {
     "title": "Interrupts / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(collectd_irq_total{instance=\"$host\", irq != 'LOC'}[$rate])",
       "legendFormat": "{{irq}}"
      }
     ]
    },
    {
     "title": "Numa Stats / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(irate(collectd_numa_vmpage_action_total{instance='$host'}[$rate]))",
       "legendFormat": "{{numa}} - {{type}}"
      }
     ]
    },
    {
     "title": "TCP Connection States",
     "type": "graph",
     "description": "For DSE ports",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collectd_tcpconns_tcp_connections{instance=\"$host\", tcpconns=~\"(70|90).*\"}",
       "legendFormat": "{{tcpconns}} - {{type}}"
      }
     ]
    },
    {
     "title": "Network Protocol Events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(collectd_protocols_protocol_counter_total{instance=\"$host\"}[$rate])",
       "legendFormat": "{{protocols}} - {{type}}"
      }
     ]
    },
    {
     "title": "Processor Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "collectd_cpufreq{instance='$host'}",
       "legendFormat": "{{cpufreq}}"
      }
     ]
    },
    {
     "title": "Page Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(collectd_vmem_vmpage_faults_majflt_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Major"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_faults_minflt_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Minor"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_action_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Action - {{vmem}}"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_io_in_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Page IO Read  "
      },
      {
       "expr": "rate(collectd_vmem_vmpage_io_out_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Page IO Write"
      }
     ]
    },
    {
     "title": "Page Cache - Layout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "((collectd_vmem_vmpage_number{instance='$host'}))",
       "legendFormat": "{{vmem}}"
      }
     ]
    },
    {
     "title": "Process Stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collectd_processes_ps_count_threads{instance='$host'}",
       "legendFormat": "Thread Count"
      },
      {
       "expr": "collectd_processes_ps_count_processes{instance='$host'}",
       "legendFormat": "Process Count"
      },
      {
       "expr": "collectd_processes_ps_state{instance='$host'}",
       "legendFormat": "Process State - {{processes}}"
      }
     ]
    }
   ]
  },
  { "title": "DSE DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Live SSTables",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_table_live_ss_table_count{instance='$host'})"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_compaction_pending_tasks{instance='$host'})"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_client_connected_native_clients{instance='$host'})"
    }
   ]
  },
  {
   "title": "Local Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(dse_table_read_latency_bucket{table=~'.*', keyspace=~'.*', instance='$host'}[$rate])) by (le)"
    }
   ]
  },
  {
   "title": "DSE JVM Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_jvm_memory_max{instance=\"$host\", memory_type='total'})",
     "legendFormat": "JVM Heap Total"
    },
    {
     "expr": "sum(dse_jvm_memory_used{instance=\"$host\", memory_type=\"non_heap\"})",
     "legendFormat": "JVM Non-Heap Used"
    },
    {
     "expr": "sum(dse_jvm_memory_used{instance=\"$host\", memory_type=\"heap\"})",
     "legendFormat": "JVM Heap Used"
    }
   ]
  }
 ]
}