{
 "title": "DSE Search Cluster",
 "tags": [ "dse" ],
 "time": { "from": "2020-12-09T01:21:49.182Z", "to": "2020-12-09T01:44:44.547Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   { "name": "rate", "label": "Rate", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(collectd_cpu_total, cluster)"
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": "label_values(collectd_cpu_total, dc)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values(collectd_cpu_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\"}, rack)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(dse_table_read_latency{cluster=~\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(dse_table_read_latency{keyspace=~\"$keyspace\"}, table)"
   },
   {
    "name": "instance",
    "query": "label_values(collectd_cpu_total{cluster=~\"$cluster\"}, instance)"
   },
   { "name": "percentile", "label": "%ile", "query": ".50,.75,.90,.95,.99" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.datastax.com\" target=\"new\"><img src=\"https://www.datastax.com/sites/default/files/content/graphics/logo/DS-logo-2019-White.png\"/></a>"
   },
   "content": "<a href=\"https://www.datastax.com\" target=\"new\"><img src=\"https://www.datastax.com/sites/default/files/content/graphics/logo/DS-logo-2019-White.png\"/></a>"
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"} >= 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(absent(sum(rate(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[2m])))) OR vector(0)"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Requests / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_table_dropped_mutations_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dse_client_connected_native_clients{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"})"
    }
   ]
  },
  {
   "title": "Client Timeouts / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_timeouts_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Total Hints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dse_storage_hints_on_disk_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"})"
    }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_table_live_disk_space_used_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"})"
    }
   ]
  },
  { "title": "Read Me", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Search Read Me",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "\n# Read Me \n\n### Search  Metrics \n#### This dashboard provides the following informations :\n* __Search advance metrics__\n * __Update Metrics__ : End to end overview of indexing pipeline\n   * __execute__ : Comprising the time spent to actually execute the index update on Lucene.\n   * __prepare__ : Comprising the time spent preparing the actual index update.\n   * __queue__ : Comprising the time spent by the index update task into the index pool.\n   * __write__ : Comprising the time spent to convert the search document and write it into the database (Available only for http)\n *__Merge Metrics__ : Lucene segment merges\n   * __warm__ : How long it takes to warm up segments to speed up cold queries.\n   * __init__ : How long it takes to initialize the merge process.\n   * __execute__ : How long it takes to execute the merge process.\n * __Query Metrics__ : Queries into the index\n   * __retrieve__   : Time spent by a node to retrieve a single row from the database\n   * __coordinate__ : Time spent by the coordinator node to distribute the query and gather/process results from shard\n   * __execute__    : Time spent by a single shard to execute the actual Lucene index query \n   * __enqueue__ : Comprises the time spent by a query request waiting for a thread to execute. (Available in 6.x)\n *__Commit Metrics__ : Flushing indexpool and Executing commit on RAM buffer\n   * __flush__ : Comprising the time spent by flushing the async indexing queue.\n   * __execute__ : Comprising the time spent by actually executing the commit on the index.\n\n *  __Search Index Pool Metrics__: For 6.x versions IndexPool Metrics are only useful while Reindexing\n   * __BackPressure Pause Nanos__ : The last backpressure pause\n   * __Processed Tasks__ :  A running total of all indexing tasks (Added irate, so value shows in graph is incremental)\n   * __Incoming/Outgoing Rate__ : Incoming/Outgoing Indexing Partition and Row tasks per minute\n   * __Queue Size__ : Partition and Row indexing tasks combined \n   * __Reindex %__ : Reindex Progress\n   * __Task Processing time Nanos__ : Last or currently processing task time\n *__Stall Metrics__ : Index workers stolen for Lucene flushing and merging (Not avaialable from DSE 6.x version)\t \n   * __flush__\n   * __merge__"
   },
   "content": "\n# Read Me \n\n### Search  Metrics \n#### This dashboard provides the following informations :\n* __Search advance metrics__\n  * __Query Metrics__ : Queries into the index\n   * __retrieve__   : Time spent by a node to retrieve a single row from the database\n   * __coordinate__ : Time spent by the coordinator node to distribute the query and gather/process results from shard\n   * __execute__    : Time spent by a single shard to execute the actual Lucene index query \n   * __enqueue__ : Comprises the time spent by a query request waiting for a thread to execute. (Available in 6.x)\n * __Update Metrics__ : End to end overview of indexing pipeline\n   * __execute__ : Comprising the time spent to actually execute the index update on Lucene.\n   * __prepare__ : Comprising the time spent preparing the actual index update.\n   * __queue__ : Comprising the time spent by the index update task into the index pool.\n   * __write__ : Comprising the time spent to convert the search document and write it into the database (Available only for http)\n *__Merge Metrics__ : Lucene segment merges\n   * __warm__ : How long it takes to warm up segments to speed up cold queries.\n   * __init__ : How long it takes to initialize the merge process.\n   * __execute__ : How long it takes to execute the merge process.\n *__Commit Metrics__ : Flushing indexpool and Executing commit on RAM buffer\n   * __flush__ : Comprising the time spent by flushing the async indexing queue.\n   * __execute__ : Comprising the time spent by actually executing the commit on the index.\n\n *  __Search Index Pool Metrics__: For 6.x versions IndexPool Metrics are only useful while Reindexing\n   * __BackPressure Pause Nanos__ : The last backpressure pause\n   * __Processed Tasks__ :  A running total of all indexing tasks (Added irate, so value shows in graph is incremental)\n   * __Incoming/Outgoing Rate__ : Incoming/Outgoing Indexing Partition and Row tasks per minute\n   * __Queue Size__ : Partition and Row indexing tasks combined \n   * __Reindex %__ : Reindex Progress\n   * __Task Processing time Nanos__ : Last or currently processing task time\n *__Stall Metrics__ : Index workers stolen for Lucene flushing and merging (Not avaialable from DSE 6.x version)\t \n   * __flush__\n   * __merge__"
  },
  { "title": "Search Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Query_Coordinate_Metrics_%ile",
   "type": "graph",
   "description": " * __Query Metrics__ : Queries into the index\n   * __coordinate__ : Time spent by the coordinator node to distribute the query and gather/process results from shard\n   ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_query_metrics_coordinate{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_coordinate_{{$keyspace}}_{{$table}}_{{$percentile}}ile"
    }
   ]
  },
  {
   "title": "Query_Execute_Metrics_%ile",
   "type": "graph",
   "description": " * __Query Metrics__ : Queries into the index\n    * __execute__    : Time spent by a single shard to execute the actual Lucene index query ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_query_metrics_execute{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_coordinate_{{$keyspace}}_{{$table}}_{{$percentile}}ile"
    }
   ]
  },
  {
   "title": "Query_Retrieve_Metrics_%ile",
   "type": "graph",
   "description": " * __Query Metrics__ : Queries into the index\n   * __retrieve__   : Time spent by a node to retrieve a single row from the database",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_query_metrics_retrieve{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_coordinate_{{$keyspace}}_{{$table}}_{{$percentile}}ile"
    }
   ]
  },
  {
   "title": "Query_Enqueue_Metrics_%ile (Available in 6.x)",
   "type": "graph",
   "description": " * __Query Metrics__ : Queries into the index\n   * __Enqueue__ : Comprises the time spent by a query request waiting for a thread to execute.\n\n   ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_query_metrics_enqueue{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_coordinate_{{$keyspace}}_{{$table}}_{{$percentile}}ile"
    }
   ]
  },
  { "title": "Search Commit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CommitMetrics_Execute_%ile",
   "type": "graph",
   "description": " * __Commit Metrics__ : Flushing indexpool and Executing commit on RAM buffer\n   * __execute__ : Comprising the time spent by actually executing the commit on the index.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_commit_metrics_execute{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_coordinate_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "CommitMetrics_Flush_%ile",
   "type": "graph",
   "description": " * __Commit Metrics__ : Flushing indexpool and Executing commit on RAM buffer\n   * __flush__ : Comprising the time spent by flushing the async indexing queue.\n   ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_commit_metrics_flush{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"\"}",
     "legendFormat": "{{$by}}_coordinate_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  { "title": "Search Merge Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Merge_Warm_Metrics_%ile",
   "type": "graph",
   "description": " * __Merge Metrics__ : Lucene segment merges\n   * __warm__ : How long it takes to warm up segments to speed up cold queries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_merge_metrics_warm{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_init_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "Merge_Init_Metrics_%ile",
   "type": "graph",
   "description": " * __Merge Metrics__ : Lucene segment merges\n   * __init__ : How long it takes to initialize the merge process.\n   ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_merge_metrics_init{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_init_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "Merge_Execute_Metrics_%ile",
   "type": "graph",
   "description": " * __Merge Metrics__ : Lucene segment merges\n   * __execute__ : How long it takes to execute the merge process.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_merge_metrics_execute{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_init_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  { "title": "Search Update Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "UpdateMetrics_Write_%ile",
   "type": "graph",
   "description": "* __Update Metrics__ : End to end overview of indexing pipeline\n   * __write__ : Comprising the time spent to convert the search document and write it into the database (Available only for http)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_update_metrics_write{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_merge_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    },
    {}
   ]
  },
  {
   "title": "UpdateMetrics_Queue_%ile",
   "type": "graph",
   "description": "* __Update Metrics__ : End to end overview of indexing pipeline\n   * __queue__ : Comprising the time spent by the index update task into the index pool.\n ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_update_metrics_queue{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_merge_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "UpdateMetrics_Prepare_%ile",
   "type": "graph",
   "description": "* __Update Metrics__ : End to end overview of indexing pipeline\n   * __prepare__ : Comprising the time spent preparing the actual index update.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_update_metrics_prepare{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_merge_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "UpdateMetrics_Execute_%ile",
   "type": "graph",
   "description": "* __Update Metrics__ : End to end overview of indexing pipeline\n   * __execute__ : Comprising the time spent to actually execute the index update on Lucene.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_update_metrics_execute{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_merge_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "Search IndexPool Metrics(For 6.x IndexPool Metrics are only useful while reindexing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "Backpressure Pause Nanos",
   "type": "graph",
   "description": "BackPressure Pause Nanos: The last backpressure pause.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "dse_solr_core_table_backpressure_pause_nanos{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"}",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{$table}}"
    }
   ]
  },
  {
   "title": "Processed Tasks",
   "type": "graph",
   "description": "Processed Tasks : A running total of all indexing tasks (Added irate, so value shows in the graph are incremental value)\n",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(dse_solr_core_table_processed_tasks{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"}[5m]) # 5.1.x/6.0.x metric",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{table}}"
    },
    {
     "expr": "irate(dse_solr_core_table_processed_tasks_total{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"}[5m]) # 6.7.x metric",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Indexing Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dse_solr_core_table_throughput{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"}",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{$table}}"
    }
   ]
  },
  {
   "title": "QueueSize",
   "type": "graph",
   "description": "Queue Size : Partition and Row indexing tasks combined\n",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dse_solr_core_table_queue_size{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"} #5.1.x/6.0.x metric",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{table}}"
    },
    {
     "expr": "dse_solr_core_table_queue_size_total{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"} #6.7.x + metric",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Task Processing time nanos",
   "type": "graph",
   "description": "Task Processing time : Last or currently processing task time\n",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "dse_solr_core_table_task_processing_time_nanos{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"} # 5.1.x/6.0.x metric",
     "legendFormat": "{{$by}}_{{keyspace}}.{{table}}"
    },
    {
     "expr": "dse_solr_core_table_task_processing_time_nanos_total{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"} # 6.7.x + metric ",
     "legendFormat": "{{$by}}_{{keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Incoming/Outgoing Rate",
   "type": "graph",
   "description": "Incoming/Outgoing Rate : Incoming/Outgoing Indexing Partition and Row tasks per minute\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dse_solr_core_table_incoming_rate{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"} ",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{table}}"
    },
    {
     "expr": "dse_solr_core_table_outgoing_rate{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"}",
     "legendFormat": "{{$by}}_{{$keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Reindex  %",
   "type": "graph",
   "description": "Reindex % : Reindex Progress",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_reindex_metrics_progress_percentage{instance=~\"$instance\",cluster=~\"$cluster\",dc=~\"$dc\",rack=~\"$rack\",keyspace=~\"$keyspace\",table=~\"$table\"}",
     "legendFormat": "{{$by}}_{{$keyspace}}_{{$table}}"
    }
   ]
  },
  {
   "title": "Search Stall Metrics (Not available in 6.x)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }
  },
  {
   "title": "Stall_Flush_Metrics_%ile",
   "type": "graph",
   "description": " * __Stall Metrics__ : Index workers stolen for Lucene flushing and merging (gone in 6.0)     \n   * __flush__\n",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_stall_metrics_flush{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_init_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  },
  {
   "title": "Stall_Merge_Metrics_%ile",
   "type": "graph",
   "description": " * __Stall Metrics__ : Index workers stolen for Lucene flushing and merging (gone in 6.0)     \n   * __merge__",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dse_solr_metric_stall_metrics_merge{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\",quantile=~\"$percentile\"}",
     "legendFormat": "{{$by}}_merge_{{$keyspace}}_{{$table}}_{{$percentile}}%ile"
    }
   ]
  }
 ]
}