{
 "title": "DSE System & Node Metrics",
 "tags": [ "dse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "label": "Rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(collectd_collectd_queue_length{}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(irate(collectd_cpu_total{instance='$host',type='idle'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'}))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "description": "Amount of memory used (ignoring page cache)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ((sum(collectd_memory{instance=\"$host\", memory=\"free\"}) + sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) + sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})) / sum(collectd_memory{instance=\"$host\"}))"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(collectd_swap{instance='$host',swap='used'}) / sum(collectd_swap{instance='$host'})) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(collectd_df_df_complex{instance='$host',df=\"root\",type=\"used\"}) / sum(collectd_df_df_complex{instance='$host',df=\"root\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(collectd_load_shortterm{instance='$host'}) / count(count(collectd_cpu_total{instance='$host'}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(collectd_load_midterm{instance='$host'}) / count(count(collectd_cpu_total{instance='$host'}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(collectd_cpu_total{instance='$host'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_memory{instance='$host'})"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_swap{instance='$host'})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{df=\"root\",instance='$host'})"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_load_shortterm{instance='$host'}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_uptime{instance='$host'}"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='system'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'})",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='user'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'}) ",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='wait'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'}) ",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='softirq'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'}) ",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(rate(collectd_cpu_total{instance='$host',type!='idle',type!='system',type!='user',type!='wait',type!='softirq'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'}) ",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(collectd_cpu_total{instance='$host',type='idle'}[$rate])) / count(collectd_cpu_total{instance='$host',type='idle'}) ",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=~\"$host\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(collectd_memory{instance=~\"$host\"}) - sum(collectd_memory{instance=~\"$host\", memory=\"free\"}) - sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) - sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) + sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(collectd_memory{instance=\"$host\", memory=\"free\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(collectd_swap{instance=\"$host\"}) - sum(collectd_swap{instance=\"$host\", swap=\"free\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Read (-) /  Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_interface_if_octets_rx_total{instance='$host'}[$rate])",
     "legendFormat": "{{interface}} read "
    },
    {
     "expr": "irate(collectd_interface_if_octets_tx_total{instance='$host'}[$rate])",
     "legendFormat": "{{interface}} write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "description": "iops",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_disk_disk_ops_read_total{instance=\"$host\",disk=~\".*\"}[$rate])",
     "legendFormat": "{{disk}} - Reads completed"
    },
    {
     "expr": "irate(collectd_disk_disk_ops_write_total{instance=\"$host\",disk=~\".*\"}[$rate])",
     "legendFormat": "{{disk}} - Writes completed"
    }
   ]
  },
  { "title": "DSE DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Live SSTables",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_table_live_ss_table_count{instance='$host'})"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_compaction_pending_tasks{instance='$host'})"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_client_connected_native_clients{instance='$host'})"
    }
   ]
  },
  {
   "title": "Local Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(dse_table_write_latency_bucket{table=~'.*', keyspace=~'.*', instance='$host'}[$rate])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DSE JVM Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_jvm_memory_max{instance=\"$host\", memory_type='total'})",
     "legendFormat": "JVM Heap Total"
    },
    {
     "expr": "sum(dse_jvm_memory_used{instance=\"$host\", memory_type=\"non_heap\"})",
     "legendFormat": "JVM Non-Heap Used"
    },
    {
     "expr": "sum(dse_jvm_memory_used{instance=\"$host\", memory_type=\"heap\"})",
     "legendFormat": "JVM Heap Used"
    }
   ]
  },
  {
   "title": "Local Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(dse_table_read_latency_bucket{table=~'.*', keyspace=~'.*', instance='$host'}[$rate])) by (le)"
    }
   ]
  }
 ]
}